services:
  app:
    image: data-process-image
    build: .
    ports:
      - 127.0.0.1:8501:8501
    environment:
      POSTGRES_HOST: app-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - app-db

  app-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - app-db-volume:/var/lib/postgresql/data

volumes:
  app-db-volume:
